/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CmdByIdResponse } from './cmdByIdResponse';


/**
 * cmd::all – Retourne toutes les commandes.
 */
export interface CmdAllResponse { 
}

