/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::byId – Retourne une commande spécifique.
 */
export interface CmdByIdResponse { 
    id?: number;
    logicalId?: string;
    generic_type?: string;
    eqType?: string;
    name?: string;
    order?: number;
    type?: string;
    subType?: string;
    eqLogic_id?: number;
    isHistorized?: boolean;
    unite?: string;
    configuration?: Array<string>;
    display?: Array<string>;
    value?: string;
    isVisible?: boolean;
    alert?: Array<string>;
    currentValue?: string;
}

