/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::byId – Retourne les détails d’une commande.
 */
export interface CmdById { 
    /**
     * ID de la commande
     */
    id: number;
}

