/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::byEqLogicId – Retourne toutes les commandes liées à un équipement.
 */
export interface CmdByEqLogicIdParam { 
    /**
     * ID de l’équipement
     */
    eqLogic_id: number;
}

