/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::byId – Retourne une commande spécifique.
 */
export interface CmdByIdResponse { 
    id?: number;
    name?: string;
    eqLogic_id?: number;
    type?: string;
    subType?: string;
    logicalId?: string;
    value?: string;
    isVisible?: boolean;
    isHistorized?: boolean;
    configuration?: object;
    display?: object;
}

