/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::event – Envoie une valeur à une commande.
 */
export interface CmdEventParam { 
    /**
     * ID de la commande
     */
    id: number;
    /**
     * Valeur à envoyer
     */
    value: string;
    /**
     * Date/heure d’exécution (optionnelle)
     */
    datetime?: string;
}

