/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::execCmd – Retourne la valeur exécutée ou son résultat.
 */
export interface CmdExecCmdResponse { 
}

