/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::execCmd – Exécute une ou plusieurs commandes Jeedom.
 */
export interface CmdExecCmdParam { 
    /**
     * ID de la commande, ou tableau d’IDs
     */
    id: number;
    /**
     * Options dépendantes du type de commande
     */
    options?: object;
}

