/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::getStatistique – Retourne les statistiques d’une commande.
 */
export interface CmdGetStatistiqueResponse { 
    min?: number;
    max?: number;
    avg?: number;
    sum?: number;
    count?: number;
}

