/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::getStatistique – Retourne les statistiques d’une commande historisée.
 */
export interface CmdGetStatistiqueParam { 
    /**
     * ID de la commande
     */
    id: number;
    /**
     * Date de début au format YYYY-MM-DD HH:mm:ss
     */
    startTime: string;
    /**
     * Date de fin au format YYYY-MM-DD HH:mm:ss
     */
    endTime: string;
}

