/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::save – Crée ou met à jour une commande.
 */
export interface CmdSave { 
    /**
     * ID de la commande (vide si création)
     */
    id?: number;
    /**
     * Nom de la commande
     */
    name: string;
    /**
     * Identifiant logique
     */
    logicalId: string;
    /**
     * Type d’équipement (virtuel, script, etc.)
     */
    eqType: string;
    /**
     * Ordre d’affichage ou exécution
     */
    order?: string;
    /**
     * Type principal (info, action, etc.)
     */
    type: string;
    /**
     * Sous-type (numeric, string, etc.)
     */
    subType: string;
    /**
     * ID de l’équipement
     */
    eqLogic_id: number;
    /**
     * Historisation (0/1)
     */
    isHistorized?: number;
    /**
     * Unité (optionnelle)
     */
    unite?: string;
    /**
     * Configuration avancée
     */
    configuration?: object;
    /**
     * Templates d’affichage
     */
    template?: object;
    /**
     * Réglages d’affichage
     */
    display?: object;
    /**
     * Contenu HTML personnalisé
     */
    html?: object;
    /**
     * Valeur par défaut (optionnelle)
     */
    value?: number;
    /**
     * Visibilité (1 par défaut)
     */
    isVisible?: number;
    /**
     * Configuration des alertes
     */
    alert?: object;
}

