/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cmd::save – Retourne les données de la commande sauvegardée.
 */
export interface CmdSaveResponse { 
    id?: number;
    name?: string;
    logicalId?: string;
    value?: string;
}

