/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * config::byKey – Retourne une valeur de configuration.
 */
export interface ConfigByKeyParam { 
    /**
     * Clé de la valeur de configuration à retourner
     */
    key: string;
    /**
     * Plugin associé (optionnel)
     */
    plugin?: string;
    /**
     * Valeur par défaut si la clé n’existe pas
     */
    'default'?: string;
}

