/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * config::save – Enregistre une valeur de configuration.
 */
export interface ConfigSave { 
    /**
     * Clé de la valeur à enregistrer
     */
    key: string;
    /**
     * Valeur à enregistrer
     */
    value: string;
    /**
     * Plugin associé (optionnel)
     */
    plugin?: string;
}

