/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * datastore::byTypeLinkIdKey – Récupère une valeur depuis le datastore.
 */
export interface DatastoreByTypeLinkIdKey { 
    /**
     * Type de donnée (ex: scenario)
     */
    type: string;
    /**
     * ID de lien (-1 pour global)
     */
    linkId: number;
    /**
     * Clé de la valeur à lire
     */
    key: string;
}

