/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::fullById – Retourne un équipement et ses commandes (type info).
 */
export interface EqLogicFullById { 
    /**
     * ID de l’équipement
     */
    id: number;
}

