/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicFullByIdResponseCmdInner } from './eqLogicFullByIdResponseCmdInner';
import { EqLogicByIdResponse } from './eqLogicByIdResponse';


/**
 * Résultat de eqLogic::fullById – Un équipement avec ses commandes.
 */
export interface EqLogicFullByIdResponse { 
    eqLogic?: EqLogicByIdResponse;
    cmd?: Array<EqLogicFullByIdResponseCmdInner>;
}

