/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::byTypeAndId – Retourne les équipements filtrés par type et ID.
 */
export interface EqLogicByTypeAndId { 
    /**
     * Liste des types d’équipements
     */
    eqType?: Array<string>;
    /**
     * Liste des IDs d’équipements
     */
    id?: Array<number>;
}

