/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicByIdResponse } from './eqLogicByIdResponse';


/**
 * Résultat de eqLogic::byTypeAndId – Liste filtrée d’équipements.
 */
export interface EqLogicByTypeAndIdResponse { 
}

