/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicByIdResponse } from './eqLogicByIdResponse';


/**
 * Résultat de eqLogic::byObjectId – Liste d’équipements liés à un objet.
 */
export interface EqLogicByObjectIdResponse { 
}

