/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EqLogicAllResponseInner { 
    id?: number;
    name?: string;
    eqType_name?: string;
    object_id?: number;
    isEnable?: boolean;
    isVisible?: boolean;
    timeout?: number;
    category?: object;
    configuration?: object;
    display?: object;
}

