/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::byType – Retourne les équipements d’un type donné.
 */
export interface EqLogicByTypeParam { 
    /**
     * Nom du plugin (type)
     */
    type: string;
}

