/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EqLogicFullByIdResponseCmdInner { 
    id?: number;
    name?: string;
    type?: string;
    subType?: string;
    value?: string;
}

