/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CmdByIdResponse } from './cmdByIdResponse';


/**
 * Résultat de eqLogic::byId – Un seul équipement. Peut avoir le détail des commandes avec eqLogic::fullById.
 */
export interface EqLogicByIdResponse { 
    id?: number;
    name?: string;
    logicalId?: string;
    generic_type?: string;
    object_id?: number;
    eqType_name?: string;
    isVisible?: boolean;
    isEnable?: boolean;
    /**
     * Liste de Paramètres d’de configuration de l’équipement
     */
    configuration?: Array<string>;
    timeout?: number;
    /**
     * liste de catégories
     */
    category?: Array<string>;
    /**
     * Liste de Paramètres d’affichage de l’équipement
     */
    display?: Array<string>;
    order?: number;
    commnent?: string;
    tags?: Array<string>;
    status?: Array<string>;
    cache?: Array<string>;
    /**
     * Liste des commandes de l’équipement. Peut être vide si eqLogic::fullById n’est pas utilisé.
     */
    cmds?: Array<CmdByIdResponse>;
}

