/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::save – Crée ou modifie un équipement.
 */
export interface EqLogicSaveParam { 
    /**
     * ID de l’équipement (vide si création)
     */
    id?: number;
    /**
     * Type d’équipement (script, virtuel, etc.)
     */
    eqType_name: string;
    /**
     * Nom de l’équipement
     */
    name: string;
    /**
     * Identifiant logique (optionnel)
     */
    logicalId?: string;
    /**
     * ID de l’objet parent (optionnel)
     */
    object_id?: number;
    /**
     * ID réel associé (optionnel)
     */
    eqReal_id?: number;
    /**
     * Visibilité (0 ou 1)
     */
    isVisible?: number;
    /**
     * Activation (0 ou 1)
     */
    isEnable?: number;
    /**
     * Données de configuration
     */
    configuration?: object;
    /**
     * Timeout (optionnel)
     */
    timeout?: number;
    /**
     * Catégories d’équipement
     */
    category?: Array<string>;
}

