/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicByIdResponse } from './eqLogicByIdResponse';


/**
 * Résultat de eqLogic::byType – Liste d’équipements d’un type donné.
 */
export interface EqLogicByTypeResponse { 
}

