/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::byId – Retourne un équipement spécifique.
 */
export interface EqLogicById { 
    /**
     * ID de l’équipement
     */
    id: number;
}

