/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * eqLogic::byObjectId – Retourne les équipements liés à un objet.
 */
export interface EqLogicByObjectIdParam { 
    /**
     * ID de l’objet
     */
    object_id: number;
}

