/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * event::changes – Retourne les changements survenus depuis un datetime donné.
 */
export interface EventChanges { 
    /**
     * Clé API autorisant l’accès
     */
    apikey: string;
    /**
     * Datetime en microsecondes à partir duquel récupérer les changements
     */
    datetime: number;
}

