/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * interact::tryToReply – Analyse une requête et exécute l’action correspondante.
 */
export interface InteractTryToReplyParam { 
    /**
     * Phrase à analyser
     */
    query: string;
    /**
     * ID de la commande à utiliser pour répondre (optionnel)
     */
    reply_cmd?: number;
}

