/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * jeedom::getUsbMapping – Retourne le mappage des ports USB.
 */
export interface JeedomGetUsbMappingResponse { 
  [key: string]: any;


}

