/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JeeObjectByIdResponse } from './jeeObjectByIdResponse';


/**
 * Résultat de jeeObject::all – Liste de tous les objets.
 */
export interface JeeObjectAllResponse { 
}

