/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicByIdResponse } from './eqLogicByIdResponse';


/**
 * Résultat de jeeObject::byId – Un seul objet Jeedom.
 */
export interface JeeObjectByIdResponse { 
    id?: number;
    name?: string;
    isVisible?: boolean;
    position?: number;
    /**
     * Configuration de l’objet, liste de clés / valeurs
     */
    configuration?: object;
    display?: object;
    father_id?: number;
    /**
     * Image de l’objet
     */
    image?: object;
    img?: string;
    /**
     * Liste des équipements de l’objet. Non valorisé sauf pour Les méthodes \"full\"
     */
    eqLogics?: Array<EqLogicByIdResponse>;
}

