/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * jeeObject::fullById – Retourne un objet complet avec ses équipements et commandes.
 */
export interface JeeObjectFullById { 
    /**
     * ID de l’objet
     */
    id: number;
}

