/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * jeeObject::save – Crée ou met à jour un objet.
 */
export interface JeeObjectSaveParam { 
    /**
     * ID de l’objet (vide si création)
     */
    id?: number;
    /**
     * Nom de l’objet
     */
    name: string;
    /**
     * ID du parent (optionnel)
     */
    father_id?: number;
    /**
     * Visibilité (0 ou 1)
     */
    isVisible?: number;
    /**
     * Position dans l’arborescence
     */
    position?: number;
    /**
     * Données de configuration
     */
    configuration?: object;
    /**
     * Paramètres d’affichage
     */
    display?: object;
}

