/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventChangesParam } from './eventChangesParam';
import { LogEmptyParam } from './logEmptyParam';
import { MessageAddParam } from './messageAddParam';
import { CmdGetStatistiqueParam } from './cmdGetStatistiqueParam';
import { PluginDeamonInfoParam } from './pluginDeamonInfoParam';
import { ScenarioChangeStateParam } from './scenarioChangeStateParam';
import { CmdByEqLogicIdParam } from './cmdByEqLogicIdParam';
import { CmdSaveParam } from './cmdSaveParam';
import { LogRemoveParam } from './logRemoveParam';
import { JeeObjectByIdParam } from './jeeObjectByIdParam';
import { LogGetParam } from './logGetParam';
import { InteractTryToReplyParam } from './interactTryToReplyParam';
import { PluginInstallParam } from './pluginInstallParam';
import { PluginRemoveParam } from './pluginRemoveParam';
import { EqLogicByTypeAndIdParam } from './eqLogicByTypeAndIdParam';
import { EqLogicFullByIdParam } from './eqLogicFullByIdParam';
import { LogListParam } from './logListParam';
import { ConfigSaveParam } from './configSaveParam';
import { ScenarioExportParam } from './scenarioExportParam';
import { TimelineByFolderParam } from './timelineByFolderParam';
import { CmdExecCmdParam } from './cmdExecCmdParam';
import { CmdByIdParam } from './cmdByIdParam';
import { PluginDeamonStartParam } from './pluginDeamonStartParam';
import { PluginDependancyInfoParam } from './pluginDependancyInfoParam';
import { EqLogicByTypeParam } from './eqLogicByTypeParam';
import { UserSaveParam } from './userSaveParam';
import { SummaryByIdParam } from './summaryByIdParam';
import { PluginDeamonStopParam } from './pluginDeamonStopParam';
import { CmdEventParam } from './cmdEventParam';
import { LogAddParam } from './logAddParam';
import { DatastoreByTypeLinkIdKeyParam } from './datastoreByTypeLinkIdKeyParam';
import { EqLogicByObjectIdParam } from './eqLogicByObjectIdParam';
import { ConfigByKeyParam } from './configByKeyParam';
import { EqLogicSaveParam } from './eqLogicSaveParam';
import { JeeObjectFullByIdParam } from './jeeObjectFullByIdParam';
import { SummaryGlobalParam } from './summaryGlobalParam';
import { UpdateDoUpdateParam } from './updateDoUpdateParam';
import { PluginListPluginParam } from './pluginListPluginParam';
import { DatastoreSaveParam } from './datastoreSaveParam';
import { ScenarioByIdParam } from './scenarioByIdParam';
import { EqLogicByIdParam } from './eqLogicByIdParam';
import { ScenarioImportParam } from './scenarioImportParam';
import { PluginDeamonChangeAutoModeParam } from './pluginDeamonChangeAutoModeParam';
import { PluginDependancyInstallParam } from './pluginDependancyInstallParam';
import { JeeObjectSaveParam } from './jeeObjectSaveParam';


/**
 * Utiliser les paramètres correspondant à la méthode sélectionnée, ex: `cmd::execCmd` = `CmdExecCmdParams` 
 */
/**
 * @type JsonRpcRequestParams
 * Utiliser les paramètres correspondant à la méthode sélectionnée, ex: `cmd::execCmd` = `CmdExecCmdParams` 
 * @export
 */
export type JsonRpcRequestParams = CmdByEqLogicIdParam | CmdByIdParam | CmdEventParam | CmdExecCmdParam | CmdGetStatistiqueParam | CmdSaveParam | ConfigByKeyParam | ConfigSaveParam | DatastoreByTypeLinkIdKeyParam | DatastoreSaveParam | EqLogicByIdParam | EqLogicByObjectIdParam | EqLogicByTypeAndIdParam | EqLogicByTypeParam | EqLogicFullByIdParam | EqLogicSaveParam | EventChangesParam | InteractTryToReplyParam | JeeObjectByIdParam | JeeObjectFullByIdParam | JeeObjectSaveParam | LogAddParam | LogEmptyParam | LogGetParam | LogListParam | LogRemoveParam | MessageAddParam | PluginDeamonChangeAutoModeParam | PluginDeamonInfoParam | PluginDeamonStartParam | PluginDeamonStopParam | PluginDependancyInfoParam | PluginDependancyInstallParam | PluginInstallParam | PluginListPluginParam | PluginRemoveParam | ScenarioByIdParam | ScenarioChangeStateParam | ScenarioExportParam | ScenarioImportParam | SummaryByIdParam | SummaryGlobalParam | TimelineByFolderParam | UpdateDoUpdateParam | UserSaveParam | object;

