/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EqLogicById } from './eqLogicById';
import { DatastoreByTypeLinkIdKey } from './datastoreByTypeLinkIdKey';
import { JeeObjectFullById } from './jeeObjectFullById';
import { ScenarioImport } from './scenarioImport';
import { EqLogicByObjectId } from './eqLogicByObjectId';
import { PluginListPlugin } from './pluginListPlugin';
import { InteractTryToReply } from './interactTryToReply';
import { TimelineByFolder } from './timelineByFolder';
import { CmdExecCmd } from './cmdExecCmd';
import { LogRemove } from './logRemove';
import { ScenarioById } from './scenarioById';
import { EventChanges } from './eventChanges';
import { EqLogicByType } from './eqLogicByType';
import { ConfigByKey } from './configByKey';
import { ScenarioChangeState } from './scenarioChangeState';
import { EqLogicByTypeAndId } from './eqLogicByTypeAndId';
import { CmdSave } from './cmdSave';
import { ConfigSave } from './configSave';
import { DatastoreSave } from './datastoreSave';
import { PluginDeamonInfo } from './pluginDeamonInfo';
import { CmdByEqLogicId } from './cmdByEqLogicId';
import { LogAdd } from './logAdd';
import { EqLogicSave } from './eqLogicSave';
import { LogEmpty } from './logEmpty';
import { PluginDependancyInstall } from './pluginDependancyInstall';
import { PluginRemove } from './pluginRemove';
import { PluginInstall } from './pluginInstall';
import { JeeObjectById } from './jeeObjectById';
import { EqLogicFullById } from './eqLogicFullById';
import { SummaryGlobal } from './summaryGlobal';
import { CmdById } from './cmdById';
import { CmdGetStatistique } from './cmdGetStatistique';
import { LogGet } from './logGet';
import { PluginDeamonStart } from './pluginDeamonStart';
import { UpdateDoUpdate } from './updateDoUpdate';
import { LogList } from './logList';
import { MessageAdd } from './messageAdd';
import { PluginDeamonStop } from './pluginDeamonStop';
import { PluginDependancyInfo } from './pluginDependancyInfo';
import { ScenarioExport } from './scenarioExport';
import { CmdEvent } from './cmdEvent';
import { JeeObjectSave } from './jeeObjectSave';
import { PluginDeamonChangeAutoMode } from './pluginDeamonChangeAutoMode';
import { SummaryById } from './summaryById';
import { UserSave } from './userSave';


/**
 * Utiliser les paramètres correspondant à la méthode sélectionnée, ex: `cmd::execCmd` = `CmdExecCmdParams` 
 */
/**
 * @type JsonRpcRequestParams
 * Utiliser les paramètres correspondant à la méthode sélectionnée, ex: `cmd::execCmd` = `CmdExecCmdParams` 
 * @export
 */
export type JsonRpcRequestParams = CmdByEqLogicId | CmdById | CmdEvent | CmdExecCmd | CmdGetStatistique | CmdSave | ConfigByKey | ConfigSave | DatastoreByTypeLinkIdKey | DatastoreSave | EqLogicById | EqLogicByObjectId | EqLogicByType | EqLogicByTypeAndId | EqLogicFullById | EqLogicSave | EventChanges | InteractTryToReply | JeeObjectById | JeeObjectFullById | JeeObjectSave | LogAdd | LogEmpty | LogGet | LogList | LogRemove | MessageAdd | PluginDeamonChangeAutoMode | PluginDeamonInfo | PluginDeamonStart | PluginDeamonStop | PluginDependancyInfo | PluginDependancyInstall | PluginInstall | PluginListPlugin | PluginRemove | ScenarioById | ScenarioChangeState | ScenarioExport | ScenarioImport | SummaryById | SummaryGlobal | TimelineByFolder | UpdateDoUpdate | UserSave | object;

