/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Détails en cas d’erreur
 */
export interface JsonRpcResponseError { 
    code?: number;
    message?: string;
}

