/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * log::add – Écrit un message dans un log.
 */
export interface LogAddParam { 
    /**
     * Nom du log
     */
    log: string;
    /**
     * Type de message (debug, info, warning, error)
     */
    type: string;
    /**
     * Message texte à écrire
     */
    message: string;
    /**
     * Identifiant logique lié au message (optionnel)
     */
    logicalId?: string;
}

