/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * log::empty – Vide un log.
 */
export interface LogEmpty { 
    /**
     * Nom du log à vider
     */
    log: string;
}

