/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * log::get – Récupère le contenu d’un log.
 */
export interface LogGet { 
    /**
     * Nom du log à récupérer
     */
    log: string;
    /**
     * Numéro de ligne de départ (optionnel)
     */
    start?: string;
    /**
     * Nombre de lignes à récupérer (optionnel)
     */
    nbLine?: string;
}

