/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * log::list – Récupère la liste des logs de Jeedom.
 */
export interface LogList { 
    /**
     * Filtre appliqué au nom des logs (optionnel)
     */
    filtre?: string;
}

