/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * message::add – Ajoute un message dans le système de log.
 */
export interface MessageAdd { 
    /**
     * Type de message (debug, info, warning, error)
     */
    type: string;
    /**
     * Texte du message
     */
    message: string;
    /**
     * Action associée (optionnelle)
     */
    action?: string;
    /**
     * Identifiant logique du message (optionnel)
     */
    logicalId?: string;
}

