/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * plugin::listPlugin – Retourne la liste des plugins.
 */
export interface PluginListPlugin { 
    /**
     * 1 pour ne retourner que les plugins activés
     */
    activateOnly?: number;
    /**
     * 1 pour trier les plugins par catégorie
     */
    orderByCaterogy?: number;
}

