/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * plugin::deamonChangeAutoMode – Change le mode de gestion du démon.
 */
export interface PluginDeamonChangeAutoModeParam { 
    /**
     * ID du plugin
     */
    plugin_id?: number;
    /**
     * Nom logique du plugin
     */
    logicalId?: string;
    /**
     * 1 pour automatique, 0 pour manuel
     */
    mode: number;
}

