/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * plugin::deamonInfo – Renvoie le statut du démon du plugin.
 */
export interface PluginDeamonInfo { 
    /**
     * ID du plugin
     */
    plugin_id?: number;
    /**
     * Nom logique du plugin
     */
    logicalId?: string;
}

