/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PluginListPluginResponse } from './pluginListPluginResponse';


/**
 * plugin::listPlugin – Liste de tous les plugins installés.
 */
export interface PluginListPluginResponses { 
}

