/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * plugin::dependancyInfo – Informations sur les dépendances du plugin.
 */
export interface PluginDependancyInfoResponse { 
  [key: string]: any;


}

