/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PluginListPluginResponse { 
    id?: number;
    name?: string;
    description?: string;
    license?: string;
    installation?: string;
    author?: string;
    require?: string;
    requireOsVersion?: string;
    category?: string;
    /**
     * Chemin du fichier info.json du plugin
     */
    filepath?: string;
    index?: string;
    display?: string;
    mobile?: string;
    eventjs?: number;
    hasDependency?: boolean;
    hasTtsEngine?: boolean;
    maxDependancyInstallTime?: number;
    hasOwnDeamon?: boolean;
    /**
     * URL du dépôt github du plugin pour déclarer un bug
     */
    issue?: string;
    /**
     * URL du changelog
     */
    changelog?: string;
    /**
     * URL de la documentation
     */
    documentation?: string;
    /**
     * URL du changelog beta
     */
    changelog_beta?: string;
    /**
     * URL de la documentation beta
     */
    documentation_beta?: string;
    /**
     * Source du plugin (market, github ...)
     */
    source?: string;
    whiteListFolders?: Array<string>;
    specialAttributes?: object;
    info?: object;
    include?: object;
    functionality?: object;
    usedSpace?: number;
}

