/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::export – Retourne les données exportables d’un scénario.
 */
export interface ScenarioExportResponse { 
  [key: string]: any;


}

