/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::byId – Retourne un scénario spécifique.
 */
export interface ScenarioById { 
    /**
     * ID du scénario
     */
    id: number;
}

