/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::byId – Retourne les détails d’un scénario.
 */
export interface ScenarioByIdResponse { 
    id?: number;
    name?: string;
    group?: string;
    isActive?: boolean;
    mode?: string;
    isVisible?: boolean;
    object_id?: number;
    configuration?: object;
    display?: object;
}

