/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::import – Importe un scénario (ou le met à jour).
 */
export interface ScenarioImportParam { 
    /**
     * ID du scénario cible (vide si création)
     */
    id?: number;
    /**
     * Nom humain du scénario (optionnel)
     */
    humanName?: string;
    /**
     * Contenu exporté depuis scenario::export
     */
    'import': object;
}

