/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScenarioByIdResponse } from './scenarioByIdResponse';


/**
 * scenario::all – Liste de tous les scénarios.
 */
export interface ScenarioAllResponse { 
}

