/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::export – Exporte un scénario.
 */
export interface ScenarioExport { 
    /**
     * ID du scénario
     */
    id: number;
}

