/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * scenario::changeState – Change l’état d’un scénario (run, stop, enable, disable).
 */
export interface ScenarioChangeState { 
    /**
     * ID du scénario
     */
    id: number;
    /**
     * Nouvel état du scénario (run, stop, enable, disable)
     */
    state: string;
}

