/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * summary::global – Retourne un résumé global ou filtré par clé.
 */
export interface SummaryGlobal { 
    /**
     * Clé spécifique du résumé (facultatif)
     */
    key?: string;
}

