/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * summary::byId – Retourne un résumé pour un objet donné.
 */
export interface SummaryById { 
    /**
     * ID de l’objet
     */
    id: number;
    /**
     * Clé spécifique du résumé (facultatif)
     */
    key?: string;
}

