/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * timeline::byFolder – Retourne tous les éléments du dossier demandé.
 */
export interface TimelineByFolder { 
    /**
     * Nom du dossier à consulter
     */
    folder: string;
}

