/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAllResponse { 
    id?: number;
    /**
     * Type de composant (plugin, core)
     */
    type?: string;
    logicalId?: string;
    name?: string;
    /**
     * Version locale du composant (ou hash, ou date au format YYYY-MM-DD HH:mm:ss)
     */
    localVersion?: string;
    /**
     * Version distante du composant (ou hash, ou date au format YYYY-MM-DD HH:mm:ss)
     */
    remoteVersion?: string;
    status?: string;
    /**
     * Configuration du composant, liste de clés / valeurs
     */
    configuration?: object;
    /**
     * Source du composant (market, github ...)
     */
    source?: string;
    /**
     * Date de la dernière mise à jour (au format YYYY-MM-DD HH:mm:ss)
     */
    updateDate?: string;
}

