/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateAllResponse } from './updateAllResponse';


/**
 * update::all – Liste de tous les composants installés.
 */
export interface UpdateAllResponses { 
}

