/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateCheckUpdateResponse } from './updateCheckUpdateResponse';


/**
 * update::checkUpdate – Liste des mises à jour disponibles.
 */
export interface UpdateCheckUpdateResponses { 
}

