/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAllResponse } from './userAllResponse';


/**
 * user::all – Liste de tous les utilisateurs.
 */
export interface UserAllResponses { 
}

