/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * user::save – Crée ou édite un utilisateur.
 */
export interface UserSaveParam { 
    /**
     * ID de l’utilisateur (obligatoire pour l’édition)
     */
    id?: number;
    /**
     * Nom d’utilisateur
     */
    login: string;
    /**
     * Mot de passe de l’utilisateur
     */
    password: string;
    /**
     * Profil de l’utilisateur (admin, user, restrict)
     */
    profile: string;
}

