/**
 * Jeedom JSON-RPC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserAllResponse { 
    id?: number;
    login?: string;
    profile?: string;
    password?: string;
    /**
     * Options de l’utilisateur, liste de clés / valeurs
     */
    options?: object;
    /**
     * Droits de l’utilisateur, liste de permissions
     */
    rights?: Array<string>;
    enable?: boolean;
    hash?: string;
}

