name: Deploy Swagger on GitHub Pages

on:
  push:
    branches:
      - master
      - open_api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # copy openai.yaml to root
      - name: Copy jeedomApiRpc.yaml to root
        run: |
          cp public/api/jeedomApiRpc.yaml ./jeedomApiRpc.yaml

      # This action generates a Swagger UI from the OpenAPI spec file and deploys it to GitHub Pages.
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: swagger-ui
          spec-file: ./jeedomApiRpc.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAGES_PAT }}
          publish_dir: swagger-ui